### PR TITLE
Implementing starry "flux" function

### PR DESCRIPTION
**Pull request by dfm**

### CODE REVIEW

**Comment by lgrcia** [comment]
Thanks @dfm! I would like to have the `flux` function working to start including the filter matrix `F` in order to have light curves of limb-darkened maps. I cannot run it on my side (see comments) probably due to missing parts.

**Comment by lgrcia** [comment]
Concerning last comment I think only a merge with branch `main` is missing

**Comment by lgrcia** [comment]
At the end this one will require the merging of several branches (`main`, `fused-rotate`, `ylm`... etc). How do you want to proceed @dfm?

**Comment by dfm** [comment]
@lgrcia — Good question! Perhaps we should start by merging all of those into main first?

**Comment by dfm** [comment]
Superseded by #111

**Pull request closed without merging**
