### PR TITLE
Fixing issue where light curve computation fails because of incorporating JPU units

### PR DESCRIPTION
**Pull request by soichiro-hattori**
This PR addresses the issue raised in #84 where the `LimbDarkLightCurve` class's `light_curve` function raises an error because of a TypeError. This error is caused by passing `pint.Quantity` objects into `jnp` functions even though a JAX array is expected. Since `pint.Quantity` objects can be correctly handled by the `jpu.numpy` functions, substituting the current `jax.numpy` function calls with the corresponding `jpu.numpy` function calls when these objects are being passed fixes this issue.

Other small changes were made so that the exposure time integration still works with the units. There is one hacky part, `dt = jnp.outer(texp.magnitude, dt) * texp.units`, where since `jnpu` does not support the `outer` function yet I'm manually separating the magnitude and the unit of `texp`, doing the computation using the usual `jnp.outer` function, and then reattaching the unit. @dfm: Maybe we could implement the outer function in `jpu.numpy`? 

The returned light curves are now 1-D vectors so indexing is not necessary (unless you actually want the first flux calculation).

### CODE REVIEW

**Comment by dfm** [comment]
Thanks @soichiro-hattori! Can you add a test to `tests/light_curves_test.py` (it would be fine to just copy the example from #84 minus the plotting)?

> Maybe we could implement the outer function in jpu.numpy?

Good idea - I'm actually surprised that it's not already there! Can you open an issue on that repo?

> The returned light curves are now 1-D vectors so indexing is not necessary (unless you actually want the first flux calculation).

This is actually a little subtle - it depends on the type of orbit! But I think that's a conversation for another thread.

**Comment by soichiro-hattori** [comment]
> Thanks @soichiro-hattori! Can you add a test to `tests/light_curves_test.py` (it would be fine to just copy the example from #84 minus the plotting)?

The updated commit should have the test in there!
> 
> > Maybe we could implement the outer function in jpu.numpy?
> 
> Good idea - I'm actually surprised that it's not already there! Can you open an issue on that repo?

Will do!

**Comment by soichiro-hattori** [comment]
Since I've added a PR on the `jpu` repo to add the `outer` function, I've updated this commit to use the `jnpu.outer` function instead of the hacky approach mentioned above.

**Comment by dfm** [comment]
Looks great to me - thanks!!

**Pull request merged**
