### PR TITLE
installation instruction

### PR DESCRIPTION
**Pull request by jiayindong**

### CODE REVIEW

**Comment by soichiro-hattori** [comment]
Could you trying adding the line `installation.md` at the end of the `index.md` file so that it looks like 
```
start
api
installation.md
tutorials/autodiff.ipynb
```
and then push it? I'm wondering if that solves the issue of Read the Docs builds failing. Thanks @jiayindong!

**Comment by jiayindong** [comment]
> Could you trying adding the line `installation.md` at the end of the `index.md` file so that it looks like
> 
> ```
> start
> api
> installation.md
> tutorials/autodiff.ipynb
> ```
> 
> and then push it? I'm wondering if that solves the issue of Read the Docs builds failing. Thanks @jiayindong!

Thanks for the suggestion, So! I've had the line added. Let's see how it goes.

**Comment by soichiro-hattori** [comment]
There's also two minor changes in the installation.md file that I commented on above! Thanks 😄

**Comment by jiayindong** [comment]
> There's also two minor changes in the installation.md file that I commented on above! Thanks 😄

@soichiro-hattori Where could I find the other two comments?

**Comment by dfm** [comment]
@soichiro-hattori — I also don't see your comments!

**Comment by soichiro-hattori** [comment]
oops sorry @jiayindong the review comments were pending since I didn't submit them!

**Comment by dfm** [comment]
Thanks @jiayindong!!

**Pull request merged**
